# Generated by Django 3.2.14 on 2022-07-13 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Number')),
                ('country_code', models.CharField(max_length=4, verbose_name='Country Code')),
                ('email', models.EmailField(help_text='Please enter your email.', max_length=254, verbose_name='Personal Email')),
                ('email2', models.EmailField(blank=True, help_text='Please enter your Business email.', max_length=254, null=True, verbose_name='Business Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
                'ordering': ('-updated_at',),
            },
        ),
    ]
